# docker-compose.yml
# Stack: PHP 8.4 + Apache, MySQL 8.4 LTS, phpMyAdmin latest, Mailpit (opcional) para probar correos
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tacos_app
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      - ./storage:/var/www/html/storage
      - ./composer.json:/var/www/html/composer.json
      - ./vendor:/var/www/html/vendor
      - ./.env:/var/www/html/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  db:
    image: mysql:8.4
    container_name: tacos_db
    environment:
      MYSQL_DATABASE: tacoscapital
      MYSQL_USER: tacos
      MYSQL_PASSWORD: tacos123
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -prootpass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: tacos_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

  # Opcional para pruebas de email SMTP en dev: http://localhost:8025
  mailpit:
    image: axllent/mailpit:latest
    container_name: tacos_mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    environment:
      MP_MAX_MESSAGES: 10000

volumes:
  dbdata:
